use_frameworks!

platform :ios, '9.0'

target 'ABSwiftUtils_Example' do
  pod 'ABSwiftUtils', :path => '../'

  target 'ABSwiftUtils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
