# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
arch:
- arm64
osx_image: xcode12.2
xcode_sdk: iphonesimulator14.2
language: objective-c

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods
- pod install --project-directory=Example
#- brew update
#- brew install xctool

- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 11"`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
- set -o pipefail
- travis_retry xcodebuild -workspace Example/ABSwiftUtils.xcworkspace -scheme ABSwiftUtils-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 11' ARCHS='arm64' ONLY_ACTIVE_ARCH=NO
- travis_retry xcodebuild test -workspace Example/ABSwiftUtils.xcworkspace -scheme ABSwiftUtils_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 11' ARCHS='arm64' ONLY_ACTIVE_ARCH=NO
- pod lib lint --verbose
