# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

arch:
- arm64
osx_image: xcode12u
xcode_sdk: iphonesimulator14.0
language: objective-c

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods
- pod install --project-directory=Example
#- brew update
#- brew install xctool

script:
- set -o pipefail
- xcodebuild -workspace Example/ABSwiftUtils.xcworkspace -scheme ABSwiftUtils-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11' ARCHS='arm64' ONLY_ACTIVE_ARCH=NO
- xcodebuild -workspace Example/ABSwiftUtils.xcworkspace -scheme ABSwiftUtils_Tests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=14.0,name=iPhone 11' ARCHS='arm64' test ONLY_ACTIVE_ARCH=NO
- pod lib lint --verbose
