# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12u
xcode_sdk: iphonesimulator14.0
language: objective-c

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods
- pod install --project-directory=Example
- brew update
- brew install xctool

script:
- set -o pipefail
- xctool -workspace Example/ABSwiftUtils.xcworkspace -scheme ABSwiftUtils-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -workspace Example/ABSwiftUtils.xcworkspace -scheme ABSwiftUtils-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --verbose
